name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Ejecuta cada 12 horas
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo
  push:
    branches:
      - main  # Solo se activa al hacer push en la rama main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Subir a la rama output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
