name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el trabajo diariamente a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: dvnber10
          svg_out_path: dist/output/snake.svg

      - name: Push Snake Animation to Repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Updated Snake animation"
          add: "dist/output/snake.svg"
